autoreconf

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21396,18 +21396,15 @@ fi
 
 
 
+ case $host_os in
+	mingw*)	unixdef="no"   ;;
+	*)	unixdef="yes"  ;;
+ esac
  # Check whether --enable-unix-transport was given.
 if test "${enable_unix_transport+set}" = set; then
   enableval=$enable_unix_transport; UNIXCONN=$enableval
 else
-  UNIXCONN=yes
-fi
-
- # Check whether --enable-tcp-transport was given.
-if test "${enable_tcp_transport+set}" = set; then
-  enableval=$enable_tcp_transport; TCPCONN=$enableval
-else
-  TCPCONN=yes
+  UNIXCONN=$unixdef
 fi
 
  { echo "$as_me:$LINENO: checking if Xtrans should support UNIX socket connections" >&5
@@ -21421,6 +21418,13 @@ _ACEOF
  fi
  { echo "$as_me:$LINENO: result: $UNIXCONN" >&5
 echo "${ECHO_T}$UNIXCONN" >&6; }
+ # Check whether --enable-tcp-transport was given.
+if test "${enable_tcp_transport+set}" = set; then
+  enableval=$enable_tcp_transport; TCPCONN=$enableval
+else
+  TCPCONN=yes
+fi
+
  { echo "$as_me:$LINENO: checking if Xtrans should support TCP socket connections" >&5
 echo $ECHO_N "checking if Xtrans should support TCP socket connections... $ECHO_C" >&6; }
  { echo "$as_me:$LINENO: result: $TCPCONN" >&5
@@ -21817,6 +21821,74 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
+
+
+ # POSIX.1g changed the type of pointer passed to getsockname/getpeername/etc.
+ { echo "$as_me:$LINENO: checking for socklen_t" >&5
+echo $ECHO_N "checking for socklen_t... $ECHO_C" >&6; }
+if test "${ac_cv_type_socklen_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+$ac_includes_default
+#include <sys/socket.h>
+
+typedef socklen_t ac__type_new_;
+int
+main ()
+{
+if ((ac__type_new_ *) 0)
+  return 0;
+if (sizeof (ac__type_new_))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_type_socklen_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_type_socklen_t=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_type_socklen_t" >&5
+echo "${ECHO_T}$ac_cv_type_socklen_t" >&6; }
+if test $ac_cv_type_socklen_t = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_SOCKLEN_T 1
+_ACEOF
+
+
+fi
+
 
 
  fi
@@ -23521,35 +23593,18 @@ fi
 #
 # Find keysymdef.h
 #
-KEYSYMDEF=""
 { echo "$as_me:$LINENO: checking keysymdef.h" >&5
 echo $ECHO_N "checking keysymdef.h... $ECHO_C" >&6; }
-for flag in $XPROTO_CFLAGS -I/usr/include; do
-	case "$KEYSYMDEF" in
-	"")
-		case "$flag" in
-		*-I*)
-			dir=`echo "$flag" | sed 's/ *-I//'`
-			file="$dir/X11/keysymdef.h"
-			if test -f "$file"; then
-				KEYSYMDEF="$file"
-			fi
-			;;
-		esac
-		;;
-	esac
-done
-case "$KEYSYMDEF" in
-"")
+dir=`pkg-config --variable=includedir xproto`
+KEYSYMDEF="$dir/X11/keysymdef.h"
+if test -f "$KEYSYMDEF"; then
+        { echo "$as_me:$LINENO: result: $KEYSYMDEF" >&5
+echo "${ECHO_T}$KEYSYMDEF" >&6; }
+else
 	{ { echo "$as_me:$LINENO: error: Cannot find keysymdef.h" >&5
 echo "$as_me: error: Cannot find keysymdef.h" >&2;}
    { (exit 1); exit 1; }; }
-	;;
-*)
-	{ echo "$as_me:$LINENO: result: $KEYSYMDEF" >&5
-echo "${ECHO_T}$KEYSYMDEF" >&6; }
-        ;;
-esac
+fi
 
 
  if test xfalse = xtrue; then
